name: Run Ansible Playbook for MariaDB via SSM

on:
  workflow_dispatch:
    inputs:
      instance_ids:
        description: 'Comma-separated list of EC2 instance IDs'
        required: true
        
permissions:
  id-token: write  # Required for OIDC authentication
  contents: read   # Required to access the repository content

jobs:
  run_playbook:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          role-to-assume: arn:aws:iam::730335291032:role/GH-action-role
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: us-east-1
          
      - name: Run Ansible Playbook using SSM
        env:
          DB_PASSWORD: ${{ secrets.DB_PASSWORD  }}  # GitHub Secret for password
        run: |
          INSTANCE_IDS="${{ github.event.inputs.instance_ids }}"  # Input instance IDs
          PLAYBOOK="s3://playbook-toantd19/MariaDB.yaml"  # Your Ansible playbook file
          SSM_DOCUMENT="AWS-RunAnsible"  # Document to execute commands

          # Run the Ansible playbook using SSM
          aws ssm send-command \
  --document-name "$SSM_DOCUMENT" \
  --document-version "1" \
  --instance-ids $INSTANCE_IDS \
  --parameters '{
    "playbook": [""],
    "playbookurl": ["'"$PLAYBOOK"'"],
    "extravars": ["SSM=True", "db_password='"$DB_PASSWORD"'"],
    "check": ["False"],
    "timeoutSeconds": ["3600"]
  }' \
  --timeout-seconds 6000 \
  --max-concurrency "50" \
  --max-errors "0" \
  --region us-east-1
